import type {Metadata} from "next"
import "./globals.css"
import {Inter as FontSans, JetBrains_Mono as FontMono} from "next/font/google"
import {cn} from "@/lib/utils"
import {Context} from "@/app/context"
import {Header} from "@/components/header"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-mono"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html suppressHydrationWarning>
      <body className={cn("flex flex-col font-sans antialiased", fontSans.variable, fontMono.variable)}>
        <Context>
          <div className="flex w-full flex-col max-w-5xl px-4 mx-auto xl:px-0">
            <Header/>
            {children}
          </div>
        </Context>
      </body>
    </html>
  )
}
